env: ''
destination: '_site'
title: CartoDB Blog
description: "All things CartoDB. New features, how-to guides, updates on events and conferences. Learn about CartoDB and online mapping with our blog."
keywords: "cartodb, map of the week, nonprofits, cartodb partners, examples"
baseurl: ""
url: "http://blog.cartodb-staging.com"

markdown: kramdown
permalink: /:title/
paginate: 10
paginate_path: page/:num
encoding: utf-8
exclude: ['img', 'README.md', 'config.rb', 'Gemfile', 'Gemfile.lock', 'node_modules', 'bower_components', 'Gruntfile.js', 'package.json', 'grunt-aws.example.json', 'grunt-aws.json']
highlighter: rouge
gems:
  - jekyll-redirect-from

cartodb-baseurl: 'http://cartodb-staging.com'
academy-baseurl: 'http://academy.cartodb.com'

analytics_property_id: ''
mixpanel_token: ''
mailchimp_id: ''

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: post
