env: 'production'
destination: '.tmp'
title: CartoDB Blog
description: "All things CartoDB. New features, how-to guides, updates on events and conferences. Learn about CartoDB and online mapping with our blog."
keywords: "cartodb, map of the week, nonprofits, cartodb partners, examples"
baseurl: ""
url: "http://blog.cartodb.com"

markdown: kramdown
permalink: /:title/
paginate: 5
paginate_path: page/:num
encoding: utf-8
exclude: ['README.md', 'config.rb', 'Gemfile', 'Gemfile.lock', 'node_modules', 'Gruntfile.js', 'package.json', 's3_website.yml']
highlighter: rouge

cartodb-baseurl: 'http://cartodb.com'
academy-baseurl: 'http://academy.cartodb.com'

analytics_property_id: 'UA-20934186-3'
mixpanel_token: '9b1d8a4fb14fa98d50615108b8b0161a'
mailchimp_id: '88c00b7e33'

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: post
